#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config top_padding         40
bspc config border_width        2
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config active_border_color \#ff0000
bspc config focused_border_color \#ff0000

bspc config external_rules_command   ~/.config/bspwm/external-rules.sh

bspc rule -a Google-chrome desktop='^1'
bspc rule -a Code desktop='^2'

bspc rule -a Zathura state=tiled
bspc rule -a "1Password" state=floating rectangle=300x300x300x300
bspc rule -a "scrcpy" desktop='^4' state=floating

